### ISSUE TITLE
Players Unable To Report Match Results (Round 4)

### ISSUE THREAD

**Issue by NikAlexander** [BattlePro/battlepro-issues#97]
Teams / Players are unable to report match results once the last round is reached.  This prohibits the 3rd place match (single elimination) and the Finalist matches from being reported.  This issue prevents a tournament from reaching completion.

**Repro:**
1. Create a test tournament (Halo, Solo, Single Elimination) or view: [1v1 Audentio Test](https://www.battlepro.com/tournaments/1v1-audentio-test.20/view-brackets)
2. Join tournament with 4 solo players / teams 
3. Host of tournament must click 'start'
4. Report match scores for round 1 (this works)
5. Attempt to report match scores for round 2 and notice lack of input boxes.  Players can not report scores once the 1st round is complete.

**Note:**
_- utilizing 'login as user' feature will be helpful for testing under multiple profiles_

**View**: unable to report scores while logged in as participant 
![no match report](https://user-images.githubusercontent.com/6005869/29903522-4a27269c-8dd2-11e7-8cc1-8530a95fce04.JPG)

**View**: successfully able to report scores for Round 1
![2](https://user-images.githubusercontent.com/6005869/29903593-a6b16d8c-8dd2-11e7-93c1-855610d1a9dd.JPG)

**Comment by kylerc** [comment]
@NikAlexander seems to be a bug with the bracket itself since it is also blocking the tournament creator from inputting scores, will be looking into this.

**Comment by kylerc** [comment]
Should be fixed on live site now.  Let me know if you find any other issues.

**Comment by NikAlexander** [comment]
This bug still exists at a later stage of a tournament.  During our most recent [ForgeHub 2v2 tournament](https://www.battlepro.com/tournaments/forgehub-2v2-throwdown.13/view-brackets) (single elimination, 32 teams), users were unable to report match results for semi-final rounds.  Staff was also unable to report match results on behalf of users.  Seems to be the same bug but for later stages of a tournament.

![brackets](https://user-images.githubusercontent.com/6005869/30005667-4b7f6c3a-909c-11e7-822d-356788322815.jpg)

**Comment by kylerc** [comment]
@NikAlexander looking into this, just to make sure before I get further into this, the tournament at https://www.battlepro.com/tournaments/forgehub-2v2-throwdown.13/view-brackets is currently in the state the issue started, right?

**Comment by kylerc** [comment]
@NikAlexander made some changes that should fix this and another bug I discovered that also would have prevented scores from saving for later stages.  Let me know if anything else comes up.
